name: PSGallery

on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Install Selenium
        run:
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module Selenium -Confirm:$false -Force;
        shell: pwsh

      - name: Building
        run: |
          .\Build\BuildModule.ps1 
        shell: pwsh        

      - name: Publishing
        run:
          $params = @{
            Path = '.\Build\SelMVP';
            NuGetApiKey = '${{ secrets.PSGALLERY }}';
            Tags = "MVP","Selenium";
            ProjectUri = [uri]::new('https://github.com/ZanattaMichael/SelMVP');
            LicenseUri = [uri]::new('https://github.com/ZanattaMichael/SelMVP/blob/master/LICENSE');
          };
          Publish-Module @params;
        shell: pwsh

