name: PSGallery

on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Building
        run: |
          .\Build\BuildModule.ps1 
        shell: pwsh        

      - name: Publishing
        run: |      
          Publish-Module -Path .\Build\SelMVP -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh

