# This is a basic workflow to help you get started with Actions

name: Current Test Status

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  WindowsPowerShellTests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install PowerShell 
      - name: Install Pester
        run:
          $ErrorActionPreference = 'Stop';
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force;
          Write-Host "Success";
        shell: powershell

      - name: Install Selenium
        run:
          $ErrorActionPreference = 'Stop';
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module Selenium -Confirm:$false -Force;
          Write-Host "Success";
        shell: powershell

      - name: InvokePesterTests
        run: |
          .\Tests\Invoke-Tests.ps1 -CI;
          if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') { exit 1 }
        shell: powershell

  PowerShellCoreTests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Pester 
      - name: InstallPester
        run:
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force;
        shell: pwsh

      - name: Install Selenium
        run:
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor;
          Set-PSRepository psgallery -InstallationPolicy trusted;
          Install-Module Selenium -Confirm:$false -Force;
        shell: pwsh

      # Runs a set of commands using the runners shell
      - name: InvokePesterTests
        run: |
          Write-Host "Not Supported on Core"
          #. .\Tests\Invoke-Tests.ps1 -CI
        shell: pwsh
       